<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourne le tableau des entités AdvertSkill référencées par les entités Advert passées en paramètre
     *
     * @param array $listAdverts Le tableau d'objets AdvertAskill liés
     */
    public function getFromAdverts($listAdverts)
    {
        if( ! empty($listAdverts)) {
            $qb = $this->createQueryBuilder('a');
            $qb
                ->where($qb->expr()->in('a.advert', '?1'))
                ->setParameter(1, $listAdverts)
            ;
            return $qb->getQuery()->getResult();
        }

        return array(); // or null?
    }
    
    public function getAdvertSkillsByAdvert($advert)
    {
        return $this
            ->createQueryBuilder('advs')
            ->innerJoin('advs.skill', 's')
            ->addSelect('s')
            ->innerJoin('advs.advert', 'ad')
            ->where('advs.advert = ?1')
            ->setParameter(1, $advert)
            ->getQuery()
            ->getResult()
        ;
    }
}
